-- Харденинг мультитенантности — ШАГ 2 (CONTRACT).
-- Снимаем ГЛОБАЛЬНЫЙ unique на tg_user_id: теперь один и тот же Telegram-человек может
-- быть отдельным лидом у РАЗНЫХ тенантов (изоляция воронок), а уникальность держит
-- составной leads_tenant_tg_user_id_key из шага 1.
--
-- ⚠️ ПРИМЕНЯТЬ ТОЛЬКО ПОСЛЕ деплоя кода с `on conflict (tenant_id, tg_user_id)`.
-- Если снять раньше — upsert старого кода (on conflict (tg_user_id)) упадёт: под его
-- ON CONFLICT не останется подходящего unique-индекса. Идемпотентно.
--
-- max_user_id (мессенджер MAX) НЕ трогаем — MAX-мост неактивен; составной ключ для него —
-- параллельный follow-up при активации MAX (leads_max_user_id_key остаётся как есть).
drop index if exists leads_tg_user_id_key;
